### ISSUE TITLE
cnspec running inside a k8s cluster: `queue is full`

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#1050]
**Describe the bug**
Running cnspec scan inside a k8s cluster resulted in `queue is full` errors.

**To Reproduce**

1. Run the mondoo-operator inside a k8s cluster
2. Deploy workloads to the cluster
3. Trigger the k8s resource scan
4. Note the error

**Expected behavior**
Queue should not be full.

**Desktop (please complete the following information):**

- mondoo-operator v1.19.2
- cnspec v9.14.0+

**Additional context**
It could be necessary to deploy a lot of workloads or run the scan multiple times to see the error.

This issue is reported on a bigger cluster.

**Comment by chris-rock** [comment]
is that fixed via https://github.com/mondoohq/cnspec/pull/1042?

**Comment by czunker** [comment]
> is that fixed via #1042?

I don't know. The fix seems valid. I think we need a new cnspec release to check whether this also fixes the error in the reported environment.
