### ISSUE TITLE
cnspec scan is returning failures for everything

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#119]
**Describe the bug**
Right now cnspec scans of a Linux host of mine is showing everything as failed even when the queries are OK.

**To Reproduce**
1. Scan a host: `cnspec scan ssh IP_OF_HOST --incognito -o full`

**Expected behavior**
Queries that pass should not fail the controls

**Screenshots**
<img width="742" alt="image" src="https://user-images.githubusercontent.com/1015200/196076914-23234e90-43d3-47b6-ae6a-f319fa7ab9fb.png">

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by TaylorMonacelli** [comment]
I stumbled across this.  I had same problem.  Its fixed in #132.
