### ISSUE TITLE
installer trigger does not work

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#1272]
**Describe the bug**
![image](https://github.com/mondoohq/cnspec/assets/827818/dbee00e3-5306-4fe4-baf8-8daa5eba8266)

https://github.com/mondoohq/cnspec/actions/runs/8799595922/job/24149395311

**Expected behavior**
The trigger should work.

**Additional context**
For other triggers, e.g. cnquery version bump in cnspec, we split this up.
The source repo triggers the target the repo:
https://github.com/mondoohq/cnquery/blob/main/.github/workflows/bump-cnspec.yml
The target repo creates the PR on event:
https://github.com/mondoohq/cnspec/blob/main/.github/workflows/cnquery-update.yml

**Comment by lexicoder** [comment]
@czunker This should now have been fixed by #1275.

**Comment by czunker** [comment]
Thanks, @lexicoder. Let's close it for now. We can re-open it when it fails during the next release.
