### ISSUE TITLE
Add a policy linting command

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#140]
**Is your feature request related to a problem? Please describe.**
Policies are often really large and it's hard to know you're including all the proper information. It would be great if we could lint them to make sure we had all the necessary fields.

**Describe the solution you'd like**
I'd like a command I could run that would ensure I had things like a desc field, audit field, remediation field, author information, a valid version number, etc.

**Describe alternatives you've considered**
I'm open for anything that allows us to check that policies have all the data necessary to share them with others.

**Comment by chris-rock** [comment]
This should be done via an enhancement for `cnspec bundle validate`. I would consider desc, audit, remediation etc as warning, not error
