### ISSUE TITLE
Add a v7 tag to the container image

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#174]
**Is your feature request related to a problem? Please describe.**
For the actions, it would be nice to have a tag with the major version.
Currently, we pull latest: https://github.com/mondoohq/actions/pull/40

We should be able to pin to a major version.

**Describe the solution you'd like**
Add a tag, currently v7, which points to the latest release version, e.g., v7.3.0.

**Describe alternatives you've considered**
We could pin to v7.3.0, but would then need to update the action with every cnspec release.

**Additional context**

**Comment by chris-rock** [comment]
Just add the tag to each image https://github.com/mondoohq/cnspec/blob/main/.goreleaser.yml#L134 as specified in https://goreleaser.com/customization/docker/#keeping-docker-images-updated-for-current-major
