### ISSUE TITLE
Windows Defender reports cnspec has a virus

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#182]
**Describe the bug**

When I download `cnspec` for windows from github: [https://github.com/mondoohq/cnspec/releases](https://github.com/mondoohq/cnspec/releases), Windows defender gives me the following...

<img width="247" alt="image" src="https://user-images.githubusercontent.com/49754039/201225280-e603e1ef-c7fd-4273-b62a-1a92a0a70670.png">

<img width="423" alt="image" src="https://user-images.githubusercontent.com/49754039/201225951-dc5adc69-ce61-4342-b57d-bcbd1c2db9a7.png">

**To Reproduce**

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI ouput to help explain your problem.

**Desktop (please complete the following information):**
- OS: Windows 10
- OS Version: [e.g. 13.0]
- Browser - Chrome

**Additional context**

**Comment by benr** [comment]
https://www.virustotal.com/ doesn't detect any trojan and we are signing the binaries, as seen here: https://github.com/mondoohq/cnspec/blob/main/.goreleaser.yml#L57

Scott tried on Windows and didn't get a similar warning.

**Comment by benr** [comment]
I tested on Windows 10 Home and could not duplicate the behavior.

**Comment by benr** [comment]
Test of Chrome downloading on Windows 10:

<img width="1920" alt="Screen Shot 2022-11-18 at 10 06 46 AM" src="https://user-images.githubusercontent.com/14073/202773291-6aec601e-075f-4765-9af4-5da349a25aa2.png">

**Comment by scottford-io** [comment]
We have not been able to reproduce this issue. The person reporting says the issue has resolved itself. I am going to close for now,  and we can reopen if it happens again.
