### ISSUE TITLE
Windows scan output formatting is not working ...

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#211]
**Describe the bug**
Output from `cnspec scan local` in PowerShell is not working ...

![Screen Shot 2022-11-25 at 11 14 08 AM](https://user-images.githubusercontent.com/49754039/204059981-fa705cdd-fd8e-4c4c-8ab8-b2ea991880a5.png)

I tested this in both AWS and GCP with WIndows 2019

**Comment by scottford-io** [comment]
Just tested on the latest release and this is still an issue...

```powershell
PS C:\Users\Administrator> ./cnspec version
cnspec 7.6.0 (c7f38eb, 2022-11-29T17:06:12Z)
```

**Comment by scottford-io** [comment]
https://www.loom.com/share/ee8414c344494a0eb6eb1173c47f4ac1

**Comment by czunker** [comment]
I could locally reproduce this with Windows 10.
