### ISSUE TITLE
terminal left in a strange state after scan

### ISSUE THREAD

**Issue by joelddiaz** [mondoohq/cnspec#230]
**Describe the bug**
After running a scan with something like `cnspec scan k8s --config ./path/to/config.json` my terminal is left not echoing back the characters I type

**To Reproduce**
1. Build cnspec
2. Run a scan like `cnspec scan k8s --discover deployments --namespace kube-system --config ./path/to/your/config.json`
3. After it completes the scan, the terminal prompt no longer is echoing back the characters typed into the keyboard.

**Expected behavior**
Terminal back in previous state.

**Screenshots or CLI Output**

```
[jdiaz@fedora cnspec (main %=)]$ ./cnspec scan k8s --discover deployments --namespace kube-system --config ~/Downloads/mondoo.json 
→ loaded configuration from /home/jdiaz/Downloads/mondoo.json using source --config
→ using service account credentials
→ discover related assets for 1 asset(s)
→ namespace filter has been set to "kube-system"
→ use cluster name from kube config cluster-name=minikube
→ resolved assets resolved-assets=1
→ connecting to asset kube-system/coredns (k8s-object)

███████████████████████████████████████████████████████████████████████████ 100% kube-system/coredns


Asset: kube-system/coredns
==========================
Data queries:
mondoo.version: "unstable"
platform.title: "Kubernetes Deployment, Kubernetes Cluster"
platform.release: ""
mondoo.jobEnvironment: {
  id: "client.mondoo.com"
  name: "Mondoo Client"
}
platform.arch: ""

Controls:


Summary (1 assets)
==================

Target:     kube-system/coredns
Datapoints: 5

Policies:
.  ..  Platform Overview Information by Mondoo

Report URL: https://console.mondoo.com/space/fleet/2IgUu43unL7aRsy7TC8Haye1vzq?spaceId=exciting-kare-592956

To get more information, please run this scan with "-o full".
[jdiaz@fedora cnspec (main %=)]$              <---- HERE I TYPED 'asdfasdfasdfasdf' AND NOTHING ON THE SCREEN
bash: asdfasdfasdfasdf: command not found...
[jdiaz@fedora cnspec (main %=)]$ 

```

**Desktop (please complete the following information):**
- OS: linux
- OS Version: Fedora 37
- Browser if applicable n/a
- Browser Version: n/a

**Additional context**
Also hearing reports of similar behavior for MacOS users.

**Comment by chris-rock** [comment]
@joelddiaz Can you check if this still happens with the latest version?

**Comment by joelddiaz** [comment]
> @joelddiaz Can you check if this still happens with the latest version?

Just built from `main` a minute ago and the issue is resolved for me.
