### ISSUE TITLE
`.all()` function does not work correctly after multiple `.where()` assertions

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnspec#248]
**Describe the bug**
When placed after an assertion that contains more than one `.where()` functions, the `all()` function will always return `true` even when it should return `false`.
 
###Steps to reproduce the behavior:

1. Example command and output with one `.where()` assertion:
```
mondoo> users.where(name == /sys/)
users.where.list: [
  0: {
    uid: 3
    name: "sys"
    gid: 3
  }
  1: {
    uid: 101
    name: "systemd-network"
    gid: 102
  }
  2: {
    uid: 102
    name: "systemd-resolve"
    gid: 103
  }
  3: {
    uid: 104
    name: "systemd-timesync"
    gid: 105
  }
  4: {
    uid: 107
    name: "syslog"
    gid: 113
  }
]
```
2. Example of the same assertion as above with another `.where()` assertion that returns empty:

```
mondoo> users.where(name == /sys/).where(_.name == 'sym')
users.where.where.list: []
```

3. Running another `.all()` assertion on top of the query above will return true

```
mondoo> users.where(name == /sys/).where(_.name == 'sym').all(_.name == 'starboard')
[ok] value: true
```

### Expected behavior

The last query above should return `false`

```
mondoo> users.where(name == /sys/).where(_.name == 'sym').all(_.name == 'starboard')
[failed] users.all()
```

### Screenshot of another example:
![image](https://user-images.githubusercontent.com/112621871/208953894-ffdf0bba-5904-40cd-8e9f-692625226e87.png)

### Mondoo Version
```
root@vagrant:/home/vagrant# ./mondoo version
Mondoo 7.8.0 (e88f93bd0, 2022-12-13T23:15:12Z)
```

**Comment by chris-rock** [comment]
@mm-weber I cannot see how this is an error. In your demonstrated chains of `where` an empty list is the result. And all entries in the empty list conform to the `.all`test. Therefore the result is `true`

**Comment by mm-weber** [comment]
I don't quite get it how a `.all(_.name == 'starboard')` check on an empty list should return `true` if there is nothing with the attribute `.name` in the empty list.

```
mondoo> test = [] test
[]
mondoo> test = [] test.all(_.name == 'starboard')
failed to compile: failed to compile: could not find call _.name
```
```
mondoo> users.where(name == /sys/).where(_.name == 'sym')
users.where.where.list: []
```
```
mondoo> users.where(name == /sys/).where(_.name == 'sym').all(_ == 'starboard')
failed to compile: cannot find operator handler: user == string
```
```
mondoo> users.where(name == /sys/).where(_.name == 'sym').all(_.name == 'starboard')
[ok] value: true
```

BUT:
```
mondoo> users.where(name == /sys/).all(_.name == 'starboard')
[failed] users.all()
  actual:   [
    0: user id = user/3/sys
    1: user id = user/101/systemd-network
    2: user id = user/102/systemd-resolve
    3: user id = user/104/systemd-timesync
    4: user id = user/107/syslog
  ]

```

Is there something I am missing logically?

**Comment by mm-weber** [comment]
Established with Patrick that it's logically correct because running `.all()` on an empty set returns `true`, right? Can be closed, might just be not that intuitive to use.
