### ISSUE TITLE
Progress bar of first item scanned shows up twice

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#305]
**Describe the bug**
When scanning a minikube clusters with `cnspec scan k8s` the first asset scanned showed up twice:

![image](https://user-images.githubusercontent.com/1015200/214382118-511a02a3-85b1-4e29-bf1b-ae69debf0ec2.png)

**Comment by mariuskimmina** [comment]
I can't reproduce this - has it been fixed already?

![image](https://github.com/mondoohq/cnspec/assets/38843153/cfd39a88-c0da-49a5-a865-c7c73ffe2fe4)

```
./cnspec version                                                                                                                   
cnspec unstable (development, unknown)
```
