### ISSUE TITLE
Unauthenticated error messages accessing some resources not clear

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#364]
**Describe the bug**
It's not clear when an unauthenticated user tries to use the `platform.cves` resource that they need to be authenticated to get data. We need an error message here that gives the user enough information to remediate this problem.

```
cnspec> platform.cves
Query encountered errors:
mondoo upstream configuration is missing
platform.cves.list: []
```

**Comment by tas50** [comment]
From Chip:

```
This client is not connected to the Mondoo platform.
For instructions on using cnspec with the Mondoo platform, see:
https://mondoo.com/docs/cnspec/cnspec-adv-install/registration/
```

**Comment by chris-rock** [comment]
Message needs to be aligned with #365

**Comment by misterpantz** [comment]
Riffing on Chip's message and consistent with https://github.com/mondoohq/cnquery/pull/1164/files#r1175548161:

```
To use this resource, you must authenticate with the Mondoo Platform. To learn how, read:  https://mondoo.com/docs/cnspec/cnspec-adv-install/registration/
```
