### ISSUE TITLE
Support for reading from stdin

### ISSUE THREAD

**Issue by michaelkrieg** [mondoohq/cnspec#402]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to render Kubernetes Helm Charts (Templates) before they become actual cluster resources. I could imagine something like this:

`helm template my-local-helmchart-directory | cnspec scan k8s -`

**Describe alternatives you've considered**
Write the helm template command's output to a temporary file.

This approach could also be interesting for other targets, like Terraform.

**Additional context**

**Comment by chris-rock** [comment]
Thank you @michaelkrieg Great idea
