### ISSUE TITLE
CLI container image scans are showing up as "online" in console

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#447]
**Describe the bug**
When running container image scans such as `cnspec scan container image ubuntu:14.04` on the CLI, the assets are showing online in the UI.

**To Reproduce**

1. Run `cnspec scan container image ubuntu:14.04"
2. Go to the space
3. Go to assets
4. Check the title of the asset in the view

**Expected behavior**
No (online) since this is a one off scan.

**Screenshots or CLI Output**
![image](https://user-images.githubusercontent.com/1015200/225455720-41b7c810-eba9-4dcd-943d-10078fb01ee9.png)

**Comment by chris-rock** [comment]
This is not a cnspec issue

**Comment by tas50** [comment]
Turns out the initial fix was a cnquery change, but then we updated the console to just skip appending this data altogether.
