### ISSUE TITLE
The link in multi-asset CI scans goes to the wrong location

### ISSUE THREAD

**Issue by tas50** [mondoohq/cnspec#484]
**Describe the bug**
This is going to require some conversation about what the possible right thing could be, but let's start with the current problem:

If you scan a Kubernetes manifest it is automatically a 2+ asset scan. The manifest file is an asset, and each of the resources within that file are also assets. When we scan with cnspec in a non-CI scenario the link given at the end of the scan is the space, which is less than ideal, but it works. When we scan in a CI environment like GH Actions we're giving users that same link. The problem is CI assets never show up in the space so this link takes them to a place where they will never be able to see the asset.

Where we could potentially link them instead:

- The manifest file on the explorer tab which would give them quick access to each repo
- The CI project page this scan would be a part of.

**Comment by vjeffrey** [comment]
project page link example:
`https://edge.console.mondoo.com/space/cicd/jobs?spaceId=SPACE&projectId=ID`

**Comment by czunker** [comment]
This also does not work for single CICD assets. We currently return the fleet URL, no matter what.

This needs a general fix.

**Comment by vjeffrey** [comment]
i thought we did some work so that a fleet url would return the correct cicd asset when used?

**Comment by tas50** [comment]
@czunker single asset scans *should* return return the single asset.

**Comment by czunker** [comment]
> i thought we did some work (ui side) so that a fleet url would return the correct cicd asset when used?

Nice, wasn't aware of this. Yes, this works. So for the single asset scan all works as expected.

**Comment by czunker** [comment]
With the linked PR, the client shows an URL as described by @vjeffrey for multi-asset CI/CD scans.

But this also requires additional data from the backend. https://gitlab.com/mondoolabs/mondoo/-/merge_requests/4001/
