### ISSUE TITLE
cnspec check fails on `true`

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#567]
**Describe the bug**
![image](https://github.com/mondoohq/cnspec/assets/49754039/7288ca94-c5de-4090-8571-909553a33d6d)

cnspec is failing a check with the result `true` which should not be a failure. This is confusing. The check also does not provide any information on what is failing

**To Reproduce**

1. `cnspec shell azure --subscription <subscription id>
2. run `azure.subscription.web.apps.all( configuration.properties["minTlsVersion"] == "1.2" )` **NOTE** may require test resources

**Expected behavior**
If a check is written with `.all()` and it fails, the results should produce a `false` to fail. Additionally, failures should produce results of what is failing.

**Comment by chris-rock** [comment]
related to https://github.com/mondoohq/cnspec/issues/532

**Comment by czunker** [comment]
CLI view:

With https://github.com/mondoohq/cnquery/pull/1211 and https://github.com/mondoohq/cnquery/pull/1219 used in cnspec, the CLI looks now like this for the above example with a failed `.all(...)` query:
```
cnspec> azure.subscription.web.apps.all( configuration.properties["minTlsVersion"] == "1.1" )
[failed] [].all()
  actual:   [
    0: azure.subscription.webService.appsite {
      configuration.properties[minTlsVersion]: "1.2"
      name: "test-cz"
      location: "East US"
      id: "/subscriptions/f1a2873a-6b27-4097-aa7c-3df51f103e96/resourceGroups/test-cz/providers/Microsoft.Web/sites/test-cz"
    }
  ]
```

**Comment by czunker** [comment]
The UI shows the default fields but is missing the actual value which was checked:
![image](https://github.com/mondoohq/cnspec/assets/827818/531d3f91-c232-4933-b535-6577d765ec46)

Will have a look at this.

**Comment by czunker** [comment]
Using the new cnquery branch in the backend, also shows the actual value in the UI:

![image](https://github.com/mondoohq/cnspec/assets/827818/1e87529c-0bb6-4117-ae84-0a66ea77832e)

**Comment by czunker** [comment]
This one is fixed with the latest cnspec release:
```
cnspec 8.13.0 (e60d270, 2023-06-06T11:56:22Z)
```
The output will get some more polish but should be a good first step forward.

@scottford-io This also fixed it in the UI for my test. Please give it a try.

I'll close it for now. Feel free to re-open or create a new issue in case I missed something.
