### ISSUE TITLE
`--pager` flag deprecated?

### ISSUE THREAD

**Issue by mm-weber** [mondoohq/cnspec#602]
The `--pager` flag as documented in `cnspec scan local --help` doesn't seem to work.

`--pager string                     Enable scan output pagination with custom pagination command. The default is 'less -R'.`

1. The default pager is STDOUT
2. The flag does return to STDOUT even when given the commands `--page 'more'` or `--pager 'less -R'`

```
$ cnspec version
cnspec v8.10.0 (e6533a4, unknown)
```

**Comment by mariuskimmina** [comment]
Sounds like it might be a very similar problem as in https://github.com/mondoohq/cnquery/pull/1259 where the flag is not parsed through correctly - will give it a closer look later on

**Comment by mariuskimmina** [comment]
After looking deeper, this argument is currently indeed not supported - there seem to be plans to have it in the future (https://github.com/mondoohq/cnquery/pull/279) but currently paging does not seem to be supported.

**Comment by chris-rock** [comment]
This has been fixed #1264
