### ISSUE TITLE
support for `cnspec scan terraform` excluding `.terraform` directory 

### ISSUE THREAD

**Issue by crcsmnky** [mondoohq/cnspec#605]
**Is your feature request related to a problem? Please describe.**
When running `cnspec scan terraform` as part of our [Atlantis pipeline](https://www.runatlantis.io/docs/using-atlantis.html), scans seem to be causing delays when trying to run other Terraform plans because of access to the `.terraform` directory

**Describe the solution you'd like**
A `cnspec` flag to explicitly exclude the `.terraform` directory when scanning HCL

**Describe alternatives you've considered**
None

**Additional context**
Steps to reproduce behavior using `cnspec shell` (edited CLI output for brevity):

```
cp example.tf /tmp/cnspec-test
cd /tmp/cnspec-test

cnspec shell terraform .

cnspec> terraform.modules
terraform.modules: []
cnspec> exit

terraform init

cnspec shell terraform .

cnspec> terraform.modules
terraform.modules: [
  0: terraform.module key=""
  1: terraform.module key="pubsub"
]
```

`example.tf`:
```
module "pubsub" {
  source  = "terraform-google-modules/pubsub/google"
  version = "~> 5.0"

  project_id = "my-project-id"
  topic      = "cft-tf-pubsub-topic"

  topic_labels = {
    foo_label = "foo_value"
    bar_label = "bar_value"
  }

  pull_subscriptions = [
    {
      name                         = "pull"
      ack_deadline_seconds         = 10
      enable_exactly_once_delivery = true
    },
  ]
}
```

**Comment by chris-rock** [comment]
fixed via https://github.com/mondoohq/cnquery/pull/2746 and released in latest cnspec + terraform provider
