### ISSUE TITLE
service mode should set the proper type for asset

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnspec#788]
**Describe the bug**

```
→ load inventory inventory-file=/Users/chris/.config/mondoo/inventory.yml
! no connection `type` provided in inventory, falling back to deprecated `backend` field
```

**To Reproduce**

Just run `cnspec serve`

**Expected behavior**

No warnings

**Comment by imilchev** [comment]
I don't see this. Also this warning is because the inventory specifies `backend` instead of `type`. This is something that needs to be fixed in the inventory

**Comment by chris-rock** [comment]
Fixed via https://github.com/mondoohq/cnquery/pull/2055
