### ISSUE TITLE
v9 reports `error` where v8 reported `unscored`

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#817]
**Describe the bug**
Comparing results between a v8 and a v9 scan against GKE, I see this:
```
🔴 check "//local.cnspec.io/run/local-execution/queries/mondoo-kubernetes-security-deployment-k8s-dashboard" got different results
   got:      {"score":0,"status":"error"}
   expected: {"score":0,"status":"unscored"}
```

This happens for this scan:
```
cnspec scan k8s -f core/mondoo-kubernetes-security.mql.yaml -o json > /tmp/v8-gke-mondoo-sec.json
```

**To Reproduce**

1. Run v8 scan with Mondoo policy against GKE edge
2. Do the same with v9
3. Compare results `policymonkey diff-report /tmp/v9-gke-mondoo-sec.json /tmp/v8-gke-mondoo-sec.json`
4. Note the error

**Expected behavior**
No difference between v8 and v9.

**Desktop (please complete the following information):**

cnspec
- v9
- v8.28.4

**Comment by czunker** [comment]
Actually, we had an error in v8 and v9. In this specific case we tried to create a `k8s.pod` resource while connected to a `k8s.deployment` or trying to create a `k8s.deployment` while connected to a `k8s.namespace`.

When running the queries in cnquery, It looks like this in v9:
```
cnquery-v9GA run k8s --discover deployments --namespaces mondoo-operator -c 'k8s.deployment.podSpec["containers"].none( _["image"].contains("kubernetes-dashboard") || _["image"].contains("kubernetesui") )'
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
[failed] [].none()
  error: rpc error: code = Unknown desc = not found
```

v8:
```
cnquery run k8s --discover deployments --namespaces mondoo-operator -c 'k8s.deployment.podSpec["containers"].none( _["image"].contains("kubernetes-dashboard") || _["image"].contains("kubernetesui") )' 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=4
[failed] [].none()
  error: failed to create resource 'k8s.deployment': could not find resource
```

The only difference is the result of the error in cnspec.

**Comment by chris-rock** [comment]
We need to improve the handling for the error in v9, especially the message. I actually think the v9 output is in general more correct.

**Comment by chris-rock** [comment]
I close this since we did quite some improvements around error handling. We continue to improve it over time. Lets open individual tickets if we see something that does not work as expected.
