### ISSUE TITLE
cnspec vuln missing --detect-cicd

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#851]
**Describe the bug**
`cnspec vuln` does not provide the `--detect-cicd` flag 

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

**Comment by chris-rock** [comment]
I do not think that is required for cnspec vuln as this is a command for local execution. Please re-open if you think this still apply.
