### ISSUE TITLE
-o full is not working

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#86]
**Describe the bug**
After running a scan such as `cnspec scan aws` a message is printed that says: `To get more information, please run this scan with "-o full"` However, if I run `cnspec scan aws -o full` I get the same message as before

**To Reproduce**
1. Open a terminal
2. run `cnspec scan aws`
3. run `cnspec scan aws -o full`

**Expected behavior**
I am expecting to see the full output with the queries and results.

**Screenshots**
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/49754039/195452462-08cea2fc-7f26-4f55-8b73-67c9ba5aa64e.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser if applicable [e.g. Chrome, Safari]
 - Version `cnspec 6.19.0 (3ca9767, 2022-10-11T19:21:29Z)`

**Additional context**

**Comment by chris-rock** [comment]
Tested in latest version and that works now. Please reopen if you find this not working as expected
