### ISSUE TITLE
`--discover all` does not work for k8s scan

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#862]
**Describe the bug**
It does not discover any asset:
```
cnspec scan k8s --discover all --config ~/demo.agent.credentials.json  --verbose                                                                                    DBG using provider k8s with connector k8s
DBG Started a new runtime (2 total)
DBG running provider plugin path=/home/christian/.config/mondoo/providers/k8s/k8s
DBG Started a new runtime (3 total)
→ loaded configuration from /home/christian/demo.agent.credentials.json using source --config
→ using service account credentials
DBG Started a new runtime (4 total)
→ discover related assets for 1 asset(s)
DBG Started a new runtime (5 total)
DBG resolved 0 assets
```

When I run it without discovery:
```
....
DBG resolved 290 assets
...
```

**To Reproduce**

1. Run a k8s scan with `--discover all`
4. Note that no assets were discovered

**Expected behavior**
With `--discover all` I would expect at least as much assets as without explicit option. It should be more assets.

**Desktop (please complete the following information):**

- cnspec 9.2.1
- provider k8s 9.0.13 with connectors: k8s

**Comment by vjeffrey** [comment]
is this fixed?

**Comment by czunker** [comment]
> is this fixed?

No, still the same issue.
