### ISSUE TITLE
cnspec scans return compliance control data when no frameworks are enabled

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/cnspec#877]
**Describe the bug**
`cnspec scan <target>` returns compliance control data when no compliance frameworks are enabled...

![image](https://github.com/mondoohq/cnspec/assets/49754039/738d7238-4969-4c3a-801f-e072d126f5ea)

**Comment by imilchev** [comment]
everything is enabled by default (in preview). That's why results are returned
