### ISSUE TITLE
cnspec cli integration tests

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnspec#902]
**Is your feature request related to a problem? Please describe.**

cnspec is running on critical infrastructure. To ensure that cnspec is very reliable we need more cli integration tests

**Describe the solution you'd like**

We want to see tests for the following scenarios:

- run `cnspec scan` and ensure that it gracefully exits, no provider instances should stay around
- run `cnspec serve` scans and ansure it gracefully exits
- test a rouge provider (does not respond in time, return wrong data types)
- run `cnspec scan` and kill the provider while cnspec scans
- kill network connection while you download a provider
- kill network connection will we report data upstream
- ensure the http timeout works properly
- test that providers are shutown with a missing heartbeat

**Comment by imilchev** [comment]
fixed in https://github.com/mondoohq/cnspec/pull/886
