### ISSUE TITLE
`cnspec vuln` does not work

### ISSUE THREAD

**Issue by czunker** [mondoohq/cnspec#911]
**Describe the bug**
```
cnspec vuln container image ubuntu:focal-20220113 
→ loaded configuration from /etc/opt/mondoo/mondoo.yml using source default
FTL failed to parse asset-name error="flag accessed but not defined: asset-name"
```

When I add the flag, I get this:
```
x unknown flag: --asset-name
```

**To Reproduce**

1. Run above command
2. Note the error

**Expected behavior**
The flag should not be required.

**Desktop (please complete the following information):**

- cnspec 9.4.0

**Comment by mariuskimmina** [comment]
@czunker I have provided a fix, please see if this solves the issue for you #912

**Comment by czunker** [comment]
> @czunker I have provided a fix, please see if this solves the issue for you #912

Nice. Thanks @mariuskimmina

**Comment by czunker** [comment]
#912 fixes this.
