### ISSUE TITLE
running a scan on windows prints a warning about "not implemented"

### ISSUE THREAD

**Issue by chris-rock** [mondoohq/cnspec#923]
**Describe the bug**

1. setup windows 2022
2. enable cis windows 2022 member server level 1
3. run `cnspec scan`

A warning is displayed:
WRN mql[processes]> could not retrieve processes socket inodes error="not implemented"

**To Reproduce**

use https://github.com/mondoohq/samples/tree/main/aws/ec2-instances and spin up `create_windows2022_cis_cnspec = true`

**Expected behavior**

no warning

**Comment by imilchev** [comment]
this should be fixed by https://github.com/mondoohq/cnquery/pull/2541
