### ISSUE TITLE
running scan on linux asset with public registry errors on k8s checks

### ISSUE THREAD

**Issue by atomic111** [mondoohq/cnspec#927]
i run a cnspec scan within a debian container. I expected that cnspec execute the linux policy, but it executes the K8s policy:

```bash
cnspec scan
! can't find any paths for providers, none are configured system-path=/opt/mondoo/providers
→ installing provider 'os' version=9.1.1
→ successfully installed os provider path=/opt/mondoo/providers/os version=9.1.1
→ no provider specified, defaulting to local. Use --help to see all providers.
→ no Mondoo configuration file provided, using defaults
! No credentials provided. Switching to --incognito mode.
→ discover related assets for 1 asset(s)

 958b7e852d97 ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────    X score


Asset: 958b7e852d97
-------------------

error: failed to compile fetched bundle: failed to validate query '//registry.mondoo.com/namespace/mondoohq/queries/mondoo-kubernetes-security-cronjob-hostpid': failed to compile query 'k8s.cronjob {
  podSpec['hostPID'] != true
}
': cannot find field 'cronjob' in k8s
failed to validate query '//registry.mondoo.com/namespace/mondoohq/queries/mondoo-kubernetes-security-deployment-limitcpu': failed to compile query 'k8s.deployment {
  initContainers {
    resources['limits']['cpu'] != null
  }
  containers {
    resources['limits']['cpu'] != null
  }
}
```

## step to reproduce:

```bash
docker run -it debian bash

apt update && apt install -y curl

bash -c "$(curl -sSL https://install.mondoo.com/sh)"

cnspec scan
```

## version

cnspec 9.5.1 (e8298bf, 2023-11-02T10:07:22Z)

**Comment by vjeffrey** [comment]
i think this is because the k8s policy has this asset filter:
```
  asset.family.contains(_ == 'linux')
  processes.where( executable == /kube-apiserver/ ).list != []
```
and we're treating that as an or?

if this is true, we can quick fix with the addition of && there, but i'm guessing this is a change from v8 - i believe we used to and those together for you in v8

**Comment by imilchev** [comment]
From what I remember, those were OR-ed together. It's good if someone confirms this before we start changing things

**Comment by vjeffrey** [comment]
confirmed that things work fine if we add the && there

**Comment by vjeffrey** [comment]
looks like the policy filters haven't really changed in over 5 months: https://github.com/mondoohq/cnspec-policies/blob/7147f65812a34520ee404c201b994c571fe5667d/core/mondoo-kubernetes-security.mql.yaml#L30

**Comment by vjeffrey** [comment]
https://github.com/mondoohq/cnspec-policies/pull/292

**Comment by imilchev** [comment]
we should fix the issue with cnquery/cnspec instead of altering the policies. This issue may happen for other policies too

**Comment by vjeffrey** [comment]
jay is looking into this...it looks like there might be a couple things going on here
