### ISSUE TITLE
Running `cnspec shell local` on a macOS host that has Docker installed but not running results in an error

### ISSUE THREAD

**Issue by charlesjohnson** [mondoohq/cnspec#94]
**Describe the bug**
Running `cnspec shell local` on a macOS host that has Docker installed but not running results in an error

**To Reproduce**

1. Run `cnspec shell local` without Docker running.
2. Observe output:
```
❯ ./cnspec shell local
→ loaded configuration from /Users/chip/.config/mondoo/mondoo.yml using source default
→ discover related assets for 1 asset(s)
→ resolved assets resolved-assets=0
x could not connect to asset error="Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" asset=
FTL could not resolve assets
```

**Expected behavior**
The shell should still open, even if the Docker daemon is not started.

**Desktop (please complete the following information):**
This bug was observed using cnspec 6.19, on macOS 12.6, with Docker Desktop 4.9.0 (80466) installed.

**Comment by chris-rock** [comment]
that was fixed in https://github.com/mondoohq/cnquery/pull/260
