### ISSUE TITLE
Running `cnspec shell` on macOS without specifying a target returns an unhelpful error message

### ISSUE THREAD

**Issue by charlesjohnson** [mondoohq/cnspec#95]
**Describe the bug**
Running `cnspec shell` on macOS without specifying a target returns an unhelpful error message

**To Reproduce**

1. Run `cnspec shell` without additional arguments.
2. Observe output:
```
❯ ./cnspec shell
→ loaded configuration from /Users/chip/.config/mondoo/mondoo.yml using source default
→ discover related assets for 0 asset(s)
→ resolved assets resolved-assets=0
FTL could not find an asset that we can connect to
```

**Expected behavior**
`cnspec shell` should either connect to local by default, or it should provide friendly output with a list of possible targets, explaining how to use them.

**Desktop (please complete the following information):**
This bug was observed using cnspec 6.19, on macOS 12.6.

**Comment by chris-rock** [comment]
fixed via https://github.com/mondoohq/cnquery/pull/344
